import { ProtocolConfig } from './types'

export const PROTOCOLS: ProtocolConfig[] = [
  {
    name: 'Lido',
    slug: 'lido',
    geckoId: 'lido-dao',
    ticker: 'LDO',
    category: 'Liquid Staking',
    chain: 'Ethereum',
    description: 'Largest liquid staking protocol for Ethereum and other PoS chains.',
  },
  {
    name: 'Aave',
    slug: 'aave',
    geckoId: 'aave',
    ticker: 'AAVE',
    category: 'Lending',
    chain: 'Ethereum',
    description: 'Decentralized non-custodial liquidity protocol for lending and borrowing.',
  },
  {
    name: 'MakerDAO',
    slug: 'makerdao',
    geckoId: 'maker',
    ticker: 'MKR',
    category: 'CDP',
    chain: 'Ethereum',
    description: 'Decentralized credit platform backing the DAI stablecoin.',
  },
  {
    name: 'Uniswap',
    slug: 'uniswap',
    geckoId: 'uniswap',
    ticker: 'UNI',
    category: 'DEX',
    chain: 'Ethereum',
    description: 'Leading decentralized exchange using automated market maker model.',
  },
  {
    name: 'Ethena',
    slug: 'ethena',
    geckoId: 'ethena',
    ticker: 'ENA',
    category: 'Synthetic',
    chain: 'Ethereum',
    description: 'Synthetic dollar protocol offering yield-bearing stablecoin USDe.',
  },
  {
    name: 'Jito',
    slug: 'jito',
    geckoId: 'jito-governance-token',
    ticker: 'JTO',
    category: 'Liquid Staking',
    chain: 'Solana',
    description: 'MEV-powered liquid staking protocol on Solana.',
  },
  {
    name: 'Raydium',
    slug: 'raydium',
    geckoId: 'raydium',
    ticker: 'RAY',
    category: 'DEX',
    chain: 'Solana',
    description: 'Automated market maker and liquidity provider on Solana.',
  },
  {
    name: 'PancakeSwap',
    slug: 'pancakeswap',
    geckoId: 'pancakeswap-token',
    ticker: 'CAKE',
    category: 'DEX',
    chain: 'BNB Chain',
    description: 'Leading DEX on BNB Chain with AMM, farming, and lottery.',
  },
  {
    name: 'Compound',
    slug: 'compound',
    geckoId: 'compound-governance-token',
    ticker: 'COMP',
    category: 'Lending',
    chain: 'Ethereum',
    description: 'Algorithmic money market protocol for lending and borrowing.',
  },
  {
    name: 'Curve',
    slug: 'curve-dex',
    geckoId: 'curve-dao-token',
    ticker: 'CRV',
    category: 'DEX',
    chain: 'Ethereum',
    description: 'DEX optimized for efficient stablecoin and pegged asset trading.',
  },
  {
    name: 'EigenLayer',
    slug: 'eigenlayer',
    geckoId: 'eigenlayer',
    ticker: 'EIGEN',
    category: 'Restaking',
    chain: 'Ethereum',
    description: 'Restaking protocol extending Ethereum security to other services.',
  },
  {
    name: 'Rocket Pool',
    slug: 'rocket-pool',
    geckoId: 'rocket-pool',
    ticker: 'RPL',
    category: 'Liquid Staking',
    chain: 'Ethereum',
    description: 'Decentralized Ethereum staking protocol with permissionless node operation.',
  },
  {
    name: 'Morpho',
    slug: 'morpho',
    geckoId: 'morpho',
    ticker: 'MORPHO',
    category: 'Lending',
    chain: 'Ethereum',
    description: 'Lending optimizer that enhances rates on existing lending protocols.',
  },
  {
    name: 'GMX',
    slug: 'gmx',
    geckoId: 'gmx',
    ticker: 'GMX',
    category: 'Derivatives',
    chain: 'Arbitrum',
    description: 'Decentralized perpetual exchange with low fees and zero price impact trades.',
  },
  {
    name: 'dYdX',
    slug: 'dydx',
    geckoId: 'dydx-chain',
    ticker: 'DYDX',
    category: 'Derivatives',
    chain: 'dYdX Chain',
    description: 'Decentralized derivatives exchange with order book trading.',
  },
  {
    name: 'Convex Finance',
    slug: 'convex-finance',
    geckoId: 'convex-finance',
    ticker: 'CVX',
    category: 'Yield',
    chain: 'Ethereum',
    description: 'Yield optimizer built on top of Curve Finance.',
  },
  {
    name: 'Aerodrome',
    slug: 'aerodrome',
    geckoId: 'aerodrome-finance',
    ticker: 'AERO',
    category: 'DEX',
    chain: 'Base',
    description: 'Central trading and liquidity marketplace on Base.',
  },
  {
    name: 'Sky (formerly Maker)',
    slug: 'sky-ecosystem',
    geckoId: 'sky',
    ticker: 'SKY',
    category: 'CDP',
    chain: 'Ethereum',
    description: 'Rebranded MakerDAO ecosystem powering the USDS stablecoin.',
  },
]

export function getProtocolBySlug(slug: string): ProtocolConfig | undefined {
  return PROTOCOLS.find((p) => p.slug === slug)
}

export function getAllSlugs(): string[] {
  return PROTOCOLS.map((p) => p.slug)
}
